/**
 * users
 * Covers Admin/HR and Employee accounts (spec 2, 3.1, 3.3).
 *
 * role:              'admin' | 'hr' | 'employee'  (app-level check, see note below)
 * employment_status: 'active' | 'inactive'
 *
 * Why plain VARCHAR instead of a native ENUM column: MySQL and Postgres
 * implement ENUM completely differently (Postgres needs a separate CREATE
 * TYPE, MySQL bakes it into the column). Using VARCHAR + validating the
 * allowed values in the backend keeps one migration file working
 * identically on both engines. Add a CHECK constraint later if you want
 * DB-level enforcement on Postgres/MySQL 8+.
 */
exports.up = function (knex) {
  return knex.schema.createTable('users', (table) => {
    table.increments('id').primary();

    table
      .integer('company_id')
      .unsigned()
      .notNullable()
      .references('id')
      .inTable('companies')
      .onDelete('CASCADE');

    // Auto-generated by the backend as OI[Initials][Year][Serial], e.g. OIRK20260007.
    // See login_id_sequences table for how the serial is generated safely.
    table.string('login_id', 30).notNullable().unique();

    table.string('name', 150).notNullable();
    table.string('email', 150).notNullable().unique();
    table.string('phone', 30).nullable();
    table.string('password_hash', 255).notNullable();

    table.string('role', 20).notNullable().defaultTo('employee'); // admin | hr | employee
    table.string('employment_status', 20).notNullable().defaultTo('active'); // active | inactive

    table.string('avatar_url', 500).nullable();
    table.string('address', 255).nullable();
    table.date('dob').nullable();
    table.text('about').nullable();
    table.string('skills', 500).nullable(); // comma-separated, per Profile.jsx

    table.string('job_title', 150).nullable();
    table.string('department', 150).nullable();
    table.date('join_date').nullable();

    table.timestamp('email_verified_at').nullable();

    table.timestamps(true, true);

    table.index(['company_id']);
  });
};

exports.down = function (knex) {
  return knex.schema.dropTableIfExists('users');
};
